### ISSUE TITLE
System.ArgumentException: At least one name server must be configured.

### ISSUE THREAD

**Issue by jixt** [sjkp/letsencrypt-azure#4]
We deployed it to our Azure environment via the deployment button of this repo, but it doesn't seem to do anything. No certificate is created at all. When running the 'RequestWildcardCertificate' function we get the following error:

`System.ArgumentException: At least one name server must be configured.
Parameter name: nameServers
   at DnsClient.LookupClient..ctor(NameServer[] nameServers)
   at DnsClient.LookupClient..ctor(IPEndPoint[] nameServers)
   at DnsClient.LookupClient..ctor(IPAddress[] nameServers)
   at LetsEncrypt.Azure.Core.V2.DnsLookupService.GetDnsClient(String[] hostnames) in D:\a\1\s\src\LetsEncrypt.Azure.Core.V2\DnsLookupService.cs:line 61
   at LetsEncrypt.Azure.Core.V2.DnsLookupService.Exists(String hostname, String dnsTxt, Int32 timeout) in D:\a\1\s\src\LetsEncrypt.Azure.Core.V2\DnsLookupService.cs:line 27
   at LetsEncrypt.Azure.Core.V2.AcmeClient.RequestDnsChallengeCertificate(IAcmeDnsRequest acmeConfig) in D:\a\1\s\src\LetsEncrypt.Azure.Core.V2\AcmeClient.cs:line 57
   at LetsEncrypt.Azure.Core.V2.LetsencryptService.Run(AcmeDnsRequest acmeDnsRequest, Int32 renewXNumberOfDaysBeforeExpiration) in D:\a\1\s\src\LetsEncrypt.Azure.Core.V2\LetsencryptService.cs:line 35
   at LetsEncrypt.Azure.FunctionV2.Helper.InstallOrRenewCertificate(ILogger log) in D:\a\1\s\examples\LetsEncrypt.Azure.FunctionV2\Helper.cs:line 54
   at LetsEncrypt.Azure.FunctionV2.RequestWildcardCertificate.Run(HttpRequest req, ILogger log) in D:\a\1\s\examples\LetsEncrypt.Azure.FunctionV2\RequestWildcardCertificate.cs:line 29`

We see that the _acme-challenge dns TXT record is created, but after that, nothing happens.

Is there extra setup that needs to be done?

**Comment by jixt** [comment]
We found out that this only works for root domain wildcards and not for subdomain wildcards. So _*.example.com_ would work, but _*.somesubdomain.example.com_ would not. 

This was important for us, so we forked the repository and did changes for this to work. For those interested, you can find the repository here:

[https://github.com/jixt/letsencrypt-azure](url)

**Comment by sjkp** [comment]
@jixt feel free to create a pull request, and I will look into merging it.
